volumes:
  db:

services:
  database:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3000:3000"
